### ISSUE TITLE
RPI4 - No HDMI Audio

### ISSUE THREAD

**Issue by myzar** [RetroGamingStuff/MAMESDLPlus#1]
RPI4 system
dtoverlay=vc4-kms-v3d

Selecting audio device with -audio-device reports audio not available, only BCM/jack works, this is the message

SDL error: ALSA: Couldn't find any hardware audio formats

this is the log

M.A.M.E. SDL Plus - v2.71
Developed by Francesco Lancioni
RetroPie Italia Forum
www.retropie-italia.it

*** Other information could be shown running M.A.M.E. from command line ***

00000.000 [INFO] - Logging started!
00000.000 [INFO] - Number of video drivers compiled into SDL: 5
00000.000 [INFO] - Driver name: x11
00000.000 [INFO] - Driver name: wayland
00000.000 [INFO] - Driver name: KMSDRM
00000.000 [INFO] - Driver name: RPI
00000.000 [INFO] - Driver name: dummy
00000.225 [INFO] - Video driver selection...
00000.225 [INFO] - --> Selected: KMSDRM
00000.225 [INFO] - SDL Video was initialized fine!
00000.225 [INFO] - SDL Image was initialized fine!
00000.248 [INFO] - SDL Audio was initialized fine!
00000.416 [INFO] - SDL Input was initialized fine!
00000.416 [INFO] - Loading rom files...
00000.452 [INFO] - Romset is good!
00000.609 [INFO] - Searching for...
00000.609 [INFO] - Artwork image path: artwork/88games.png
00000.609 [WARNING] - Artwork loading/creation: is artwork/88games.png present?
00000.668 [INFO] - Screen width: 1920
00000.668 [INFO] - Screen height: 1080
00000.668 [INFO] - Framebuffer width: 1920
00000.668 [INFO] - Framebuffer height: 1080
00000.668 [INFO] - Game Native width: 304
00000.668 [INFO] - Game Native height: 224
00000.668 [INFO] - Cabinet game aspect ratio: 1.33
00000.668 [INFO] - Square game pixel
00000.668 [INFO] - Added joypad: Microsoft X-Box 360 pad (Instance ID: 0)
00000.668 [INFO] - Connected joypad/s: 1
00002.392 [INFO] - Number of available audio devices: 2
00002.392 [INFO] - Device name: [0] vc4-hdmi-0, MAI PCM i2s-hifi-0
00002.392 [INFO] - Device name: [1] vc4-hdmi-1, MAI PCM i2s-hifi-0
00002.392 [INFO] - Audio device selection...
00002.425 [INFO] - SDL error: ALSA: Couldn't find any hardware audio formats
00002.425 [INFO] - Skipped: vc4-hdmi-0, MAI PCM i2s-hifi-0
00002.425 [INFO] - SDL error: ALSA: Couldn't open audio device: No such device
00002.425 [INFO] - Skipped: vc4-hdmi-1, MAI PCM i2s-hifi-0
00002.425 [ERROR] - No audio, FPS synchronization will fail!

00002.425 [INFO] - The game is running!!!

00034.103 [INFO] - Game exited!!!
00034.103 [INFO] - *** Execution summary ***
00034.103 [INFO] - Main loop frequency: 44.848560 Hz
00034.103 [INFO] - Nominal FPS: 60.00
00034.104 [INFO] - Real FPS: 29.909546
00034.104 [INFO] - Play time: 31.729 seconds

M.A.M.E. SDL Plus - v2.71
Developed by Francesco Lancioni
RetroPie Italia Forum
www.retropie-italia.it

**Comment by RetroGamingStuff** [comment]
Install pulseaudio with:
`sudo apt install pulseaudio`

or

remove it before reinstall:
`sudo apt remove --purge pulseaudio`
`sudo apt install pulseaudio`

then reboot with:
`sudo shutdown -r now`

After that run Raspberry Pi configuration with:
`sudo raspi-config`

In audio configuration you must see this:
```
0 Headphones
1 MAI PCM i2s-hifi-0
```

so select **MAI PCM i2s-hifi-0**. If you only see this:
`0 Headphones`

**it is not a problem of M.A.M.E. SDL Plus**. In that case retry to launch the emulator, reboot and relaunch `raspi-config`. This is an old bug of raspi-config/pulseaudio/whatever.

P.S.: also read [this](https://github.com/RetroGamingStuff/MAMESDLPlus/blob/master/README_en.md#real-crt-version) regarding poor performance

**Comment by myzar** [comment]
Sorry about english , nope i will not install pulseaudio garbage , that thing sucks horribly and every other sdl program like PPSSPPSDL , ADVANCEMAME , mamestandalone and many other ports using SDL and Alsa work just fine. in raspi-config i've 

https://postimg.cc/bDTHWGMr/baf1d169

The specific error msg is 

SDL error: ALSA: Couldn't find any hardware audio formats

according to the SDL source that is 

https://github.com/emscripten-ports/SDL2/blob/master/src/audio/alsa/SDL_alsa_audio.c#L622

what kind of sample format are you requesting ?

**Comment by RetroGamingStuff** [comment]
Requested audio format in emulator source code is `AUDIO_S16SYS`, that is translated to one of these according to [SDL source code](https://github.com/libsdl-org/SDL/blob/main/include/SDL_audio.h):
```
#if SDL_BYTEORDER == SDL_LIL_ENDIAN
#define AUDIO_U16SYS    AUDIO_U16LSB
#define AUDIO_S16SYS    AUDIO_S16LSB
#define AUDIO_S32SYS    AUDIO_S32LSB
#define AUDIO_F32SYS    AUDIO_F32LSB
#else
#define AUDIO_U16SYS    AUDIO_U16MSB
#define AUDIO_S16SYS    AUDIO_S16MSB
#define AUDIO_S32SYS    AUDIO_S32MSB
#define AUDIO_F32SYS    AUDIO_F32MSB
#endif
```
So the format is `AUDIO_S16LSB` or `AUDIO_S16MSB`.

That error is related to the response of this SDL code call, according with your link:
`SDL_FirstAudioFormat(this->spec.format)`

**and it's not a bug in M.A.M.E. SDL Plus**.

What Raspberry Pi OS version are you using? Or is it RetroPie? What version?

**Comment by padremayi** [comment]
Your is a common problem, read [this](https://forums.raspberrypi.com/viewtopic.php?t=330349).

As wrote before you have to select the default audio device with `raspi-config`. Additionally, when I close the emulator I see this on the command line:

```
Graphic card vendor: Broadcom
Renderer: V3D 4.2
GL version: 2.1 Mesa 22.0.4
GLSL version: 1.20
```

and these snippets in M.A.M.E. SDL Plus log:

```
...
00000.276 [INFO] - Video driver selection...
00000.276 [INFO] - --> Selected: x11
...
```

```
...
00002.690 [INFO] - Number of available audio devices: 2
00002.690 [INFO] - Device name: [0] Built-in Audio Analog Stereo
00002.690 [INFO] - Device name: [1] Built-in Audio Digital Stereo (HDMI)
00002.690 [INFO] - Audio device selection...
00002.690 [INFO] - Device [1] requested
00002.709 [INFO] - --> Selected: Built-in Audio Digital Stereo (HDMI)
...
```

In your log you have **KMSDRM** selected as **video** driver and I can't see the log where you requested a specific **audio** device. At the end I have these options enabled and set in my config.txt and audio works fine:

```
# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Disable compensation for displays with overscan
disable_overscan=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[pi4]
# Run as fast as firmware / board allows
arm_boost=1
gpu_mem=64
```

You have a problem with your environment, why don't you share the Raspberry Pi OS (or RetroPie) version? Clean operating system or preconfigured garbage download from the net?

**Comment by myzar** [comment]
> Your is a common problem, read [this](https://forums.raspberrypi.com/viewtopic.php?t=330349).

yes you are right that's my problem my system is 

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Linux retropie 5.15.56-v7l+ #1 SMP Mon Jul 25 22:40:14 CEST 2022 armv7l GNU/Linux

MamesdlPlus says:

00004.133 [INFO] - Number of available audio devices: 3
00004.133 [INFO] - Device name: [0] bcm2835 Headphones, bcm2835 Headphones
00004.133 [INFO] - Device name: [1] vc4-hdmi-0, MAI PCM i2s-hifi-0
00004.133 [INFO] - Device name: [2] vc4-hdmi-1, MAI PCM i2s-hifi-0
00004.133 [INFO] - Audio device selection...
00004.133 [INFO] - Device [1] requested
00004.166 [INFO] - SDL error: ALSA: Couldn't find any hardware audio formats
00004.166 [INFO] - Skipped: bcm2835 Headphones, bcm2835 Headphones
00004.198 [INFO] - SDL error: ALSA: Couldn't find any hardware audio formats
00004.198 [INFO] - Skipped: vc4-hdmi-0, MAI PCM i2s-hifi-0
00004.230 [INFO] - SDL error: ALSA: Couldn't find any hardware audio formats
00004.230 [INFO] - Skipped: vc4-hdmi-1, MAI PCM i2s-hifi-0
00004.230 [ERROR] - No audio, FPS synchronization will fail!

and aplay doesn't work like in the post you linked

root@retropie:~# aplay -D plughw:0,0 /usr/share/sounds/alsa/Front_Right.wav
Playing WAVE '/usr/share/sounds/alsa/Front_Right.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Mono
aplay: set_params:1343: Sample format non available
Available formats:
- IEC958_SUBFRAME_LE

Unfortunately there's no solution in that thread and everything else just works including other sdl stuff like advancemame , mamesdlplus is the only program refusing to play hdmi audio , so no idea i guess i'll give up and live without this nice mame :)

**Comment by RetroGamingStuff** [comment]
I would give it a try with `pulseaudio`, by the way it is an environment problem, not a bug.

P.S.: try to uncomment option `hdmi_drive=2` in config.txt
